fix: metadata is properly built
ubiquity-os/plugin-sdk pull request #42
Opened 2024-12-19 15:12 UTC by gentlementlegen

Resolves #41

2024-12-20 16:12 UTC, gentlementlegen commented
## What are the changes

Currently the metadata headers are broken and do not display any info when used through the SDK. Also, Workers could not display any relevant information either. This is fixed by this pull-request (thank you @keyrxng for the code head start).

I determined that the most important info we always use is:
- instigator of the event (there are many times we wonder what happened because someone triggered the bot then deleted its comments so it looked strange)
- the revision of the action / worker used
- the URL to the run for actions because it is really hard to find the corresponding run, the URL to the dashboard for workers because it is very tedious to change the time range to match the comment within the issue

So now a header would look like the following:
- `UbiquityOS - @gentlementlegen - https://dash.cloudflare.com/1758eb0455a5d4e15ab52916ecb4991b/workers/services/view/ubiquity-os-command-query-user-development/production/observability/logs?granularity=0&time=%7B%22type%22%3A%22absolute%22%2C%22to%22%3A1734701838132%2C%22from%22%3A1734701718132%7D - queryUser - 6533250f-1e1a-4259-9f40-40f5c2018dbb` for a Worker posted message
- `UbiquityOS - @gentlementlegen - https://github.com/Meniole/text-conversation-rewards/actions/runs/12431861924 - run - 1ad41aef8f27319064c2bf05fbad5ec3e3238e25` for an Action posted message

Which I think gives us the most important data and an easy way to find more detailed logs.

For convenience, I also added an option to post message `raw` that allow to post the body as sent in the function without our `Logger` formatting which is useful when you want to output complex data, like we do for `text-conversation-reward` results or even `query-user` when showing the user its wallet.

QA: https://github.com/Meniole/text-conversation-rewards/issues/43 (not sure if you can see the metadata though but it's the one I copy pasted here).

Workers will need to upload one more secret that will help finding the user, and enable an option in their `toml` configuration that allows to fetch their ID, I will also carry out these changes if this is ok.

Also at this time, not every plugin uses our SDK to post so this has to be updated over time.

2024-12-20 16:14 UTC, gentlementlegen commented
Rfc @whilefoo @0x4007 I will fix `Jest` if the changes are ok.

2024-12-29 05:47 UTC, 0x4007 commented on README.md
> +The `postComment` function enables users to easily post a comment to an issue, a pull-request or even a conversation.
```suggestion
The `postComment` function enables users to easily post a comment to an issue, a pull-request, or a pull request review thread.
```

2024-12-30 04:29 UTC, 0x4007 commented
Code changes look fine. 

Interested to see the renderer metadata in a QA example.

2024-12-30 06:06 UTC, gentlementlegen commented
@0x4007 Sorry didn't post QA because I figured you would not be able to see the metadata from my organization. Lemme display some results then.

2024-12-30 13:05 UTC, 0x4007 commented
Looks informative but what is the second field with the value of your username?

2024-12-30 13:07 UTC, gentlementlegen commented
@0x4007 It is the name of the person that instigated the run. I thought it was useful information because many times we were wondering why some comments were posted, and it was because the person who posted these comments deleted them afterwards.

2024-12-30 13:35 UTC, 0x4007 commented
Sure we can leave it then.

2025-01-01 19:23 UTC, whilefoo requested changes

2025-01-01 19:23 UTC, whilefoo commented on src/comment.ts
> +  }
You could just set `logMessage` to `content` in the first if statement and then you don't need this if statement

2025-01-01 19:23 UTC, whilefoo commented on src/comment.ts
> +  } else if (message.metadata) {
why not `message instanceof LogReturn`?

2025-01-01 19:23 UTC, whilefoo commented on src/comment.ts
> +    }
What's the point of assigning it again? I think it would look cleaner to set it once:
```js
metadata = {
  message: message.metadata.message,
  stack: message.metadata.stack || message.metadata.error?.stack,
  caller: message.metadata.caller || message.metadata.error?.stack?.split("\n")[2]?.match(/at (\S+)/)?.[1],
}
```

2025-01-02 07:40 UTC, gentlementlegen commented on src/server.ts
> +    PluginRuntimeInfo.getInstance({ ...env, CLOUFLARE_WORKER_NAME: workerName });
The `ref` is automatically populated when using `fetch` and holds the value of the targeted URL, so no need to manually set it.

It is a protected singleton so no shady stuff should happen, I tested it without issues so far. The problem is that the function can't access the `context` of the Worker so I have to store this somewhere. Storing primitives is usually fine, storing references to object instances causes random things to happen.

Maybe `hostname` holds the same value, I'll test.

2025-01-02 07:42 UTC, gentlementlegen commented on src/comment.ts
> +  }
It should be the account where the GitHub app is installed, it is simply a failsafe in case there is no user in the payload, I can remove it if you deem it unnecessary.

2025-01-02 07:50 UTC, gentlementlegen commented on src/comment.ts
> +  } else if (message.metadata) {
the `metadata` can technically be empty, which is why it is checked there:
<img width="754" alt="image" src="https://github.com/user-attachments/assets/a5f74730-0a10-4061-ab7e-5e3c281beea3" />

2025-01-02 08:38 UTC, gentlementlegen commented on src/server.ts
> +    PluginRuntimeInfo.getInstance({ ...env, CLOUFLARE_WORKER_NAME: workerName });
https://github.com/ubiquity-os/plugin-sdk/pull/42/commits/bceb92bcb5b82ef826d514bd88ea29ec9dec37c6

2025-01-02 08:41 UTC, 0x4007 commented
Actually the invoker field should be last for search reasons.

2025-01-03 16:00 UTC, whilefoo commented on src/comment.ts
> +  }
it's fine, I just didn't know what it is

2025-01-03 16:03 UTC, whilefoo commented on src/server.ts
> +    PluginRuntimeInfo.getInstance({ ...env, CLOUFLARE_WORKER_NAME: workerName });
> The `ref` is automatically populated when using `fetch` and holds the value of the targeted URL, so no need to manually set it.

First time I'm hearing of this. Why would `fetch` manipulate the body of a request? I only know that `Host` header gets filled automatically, maybe I'm missing something

2025-01-05 12:44 UTC, 0x4007 approved these changes

2025-01-05 12:51 UTC, gentlementlegen commented on src/comment.ts
> +const HEADER_NAME = "UbiquityOS";
This is the SDK package, not sure what you mean exactly?

2025-01-05 12:58 UTC, whilefoo commented
@gentlementlegen I think you missed my [comment](https://github.com/ubiquity-os/plugin-sdk/pull/42#discussion_r1901933841)

2025-01-05 13:09 UTC, 0x4007 commented on src/comment.ts
> +const HEADER_NAME = "UbiquityOS";
I didn't mean to post this pending comment

2025-01-05 13:12 UTC, gentlementlegen commented
@whilefoo Apologies I did miss it, addressing this now.

2025-01-05 15:47 UTC, gentlementlegen commented on src/server.ts
> +    PluginRuntimeInfo.getInstance({ ...env, CLOUFLARE_WORKER_NAME: workerName });
I was totally confused sorry, the `ref` is populated by our kernel, either with the Action name or the Worker url, see [this code](https://github.com/ubiquity-os/ubiquity-os-kernel/blob/3d7fe46223c48e8c4e84f83675b4c4884649dc0c/src/github/handlers/index.ts#L102). I was thinking about the `hostname` part.

And you are correct about the splitting problem, will address this and link you a QA.

2025-01-05 16:12 UTC, gentlementlegen commented on src/server.ts
> +    PluginRuntimeInfo.getInstance({ ...env, CLOUFLARE_WORKER_NAME: workerName });
New QA: https://dash.cloudflare.com/1758eb0455a5d4e15ab52916ecb4991b/workers/services/view/ubiquity-os-command-query-user-development/production/observability/logs?granularity=0&time=%7B%22type%22%3A%22absolute%22%2C%22to%22%3A1736093557425%2C%22from%22%3A1736093437425%7D

2025-01-05 18:19 UTC, whilefoo approved these changes

2025-01-06 00:07 UTC, merged

2025-01-15 19:56 UTC, Keyrxng commented
> (thank you @Keyrxng for the code head start).

Lmao happy to help I guess 😅